### ISSUE TITLE
Android-Device-Tuna and Android-Device-Maguro can't fetch

### ISSUE THREAD

**Issue by ghost** [mozilla-b2g/b2g-manifest#284]
Fetching project android-device-maguro
fatal: Couldn't find remote ref refs/heads/v1.0.0
fatal: Couldn't find remote ref refs/heads/v1.0.0
Fetching projects:  74% (61/82)  Fetching project platform/external/tagsoup
Fetching projects:  75% (62/82)  Fetching project platform/external/apache-http
Fetching projects:  76% (63/82)  Fetching project rilproxy
Fetching projects:  78% (64/82)  Fetching project platform/external/expat
Fetching projects:  79% (65/82)  Fetching project platform/hardware/ti/omap4xxx
Fetching projects:  80% (66/82)  Fetching project platform/external/harfbuzz
Fetching projects:  81% (67/82)  Fetching project platform/external/bzip2
Fetching projects:  82% (68/82)  Fetching project platform/frameworks/opt/emoji
Fetching projects:  84% (69/82)  Fetching project platform/frameworks/support
Fetching projects:  85% (70/82)  Fetching project platform/abi/cpp
Fetching projects:  86% (71/82)  Fetching project platform/external/tremolo
Fetching projects:  87% (72/82)  Fetching project screencap-gonk
Fetching projects:  89% (73/82)  Fetching project platform/libcore
Fetching projects:  90% (74/82)  Fetching project platform/external/libvpx
Fetching projects:  91% (75/82)  Fetching project platform/external/dnsmasq
Fetching projects:  92% (76/82)  Fetching project platform/system/core
Fetching projects:  93% (77/82)  Fetching project device/common
Fetching projects:  95% (78/82)  Fetching project platform/bionic
Fetching projects:  97% (80/82)  fatal: Couldn't find remote ref refs/heads/v1.0.0
fatal: Couldn't find remote ref refs/heads/v1.0.0
error: Cannot fetch android-device-tuna
warn: --force-broken, continuing to sync
Fetching projects:  98% (81/82)  error: Cannot fetch android-device-maguro
warn: --force-broken, continuing to sync
Fetching projects: 100% (82/82), done.  

Run |./build.sh| to start building
blmvxer@blmvxer-Satellite-C875:~/B2G$

**Comment by blmvxer** [comment]
I've also pulled my system from my device and told ./config.sh where it was and it still tries to contact the online repository for the binary blobs.
